name: Build PyInstaller Apps

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-windows:
    name: Build Windows EXE
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build Windows Executable
        run: pyinstaller build_win.spec

      - name: Upload .exe
        uses: actions/upload-artifact@v4
        with:
          name: windows-exe
          path: dist/VQ Image 2 WebP Converter.exe

      - name: Extract version
        id: get_version
        run: |
          import re, os
          version = "0.0.0"
          with open("main.py", "r") as f:
              for line in f:
                  match = re.match(r'version\s*=\s*["\'](\d+\.\d+\.\d+)["\']', line)
                  if match:
                      version = match.group(1)
                      break
          with open(os.environ["GITHUB_OUTPUT"], "a") as fh:
              print(f"version={version}", file=fh)
        shell: python

      - name: Zip .exe
        run: |
          Compress-Archive -Path "dist\\VQ Image 2 WebP Converter.exe" -DestinationPath "dist\\vq-image2webp-windows.zip"
        shell: pwsh

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.get_version.outputs.version }}
          name: Release v${{ steps.get_version.outputs.version }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload to Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.get_version.outputs.version }}
          files: |
            dist/vq-image2webp-windows.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-macos:
    name: Build macOS App
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build macOS App
        run: pyinstaller build_mac.spec

      - name: List output files
        run: ls -l dist

      - name: Upload .app
        uses: actions/upload-artifact@v4
        with:
          name: macos-app
          path: dist/VQ Image 2 WebP Converter.app

      - name: Extract version
        id: get_version
        run: |
          import re, os
          version = "0.0.0"
          with open("main.py", "r") as f:
              for line in f:
                  match = re.match(r'version\s*=\s*["\'](\d+\.\d+\.\d+)["\']', line)
                  if match:
                      version = match.group(1)
                      break
          with open(os.environ["GITHUB_OUTPUT"], "a") as fh:
              print(f"version={version}", file=fh)
        shell: python

      - name: Zip .app bundle
        run: |
          zip -r "dist/vq-image2webp-mac.zip" "dist/VQ Image 2 WebP Converter.app"

      - name: Upload to Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.get_version.outputs.version }}
          files: |
            dist/vq-image2webp-mac.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}