name: Build PyInstaller Apps

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-windows:
    name: Build Windows EXE
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build Windows Executable
        run: pyinstaller build_win.spec

      - name: Create ZIP Archive
        run: |
          powershell Compress-Archive -Path dist\* -DestinationPath windows_build.zip

      - name: Upload Windows ZIP
        uses: actions/upload-artifact@v4
        with:
          name: windows-zip
          path: windows_build.zip

  build-macos:
    name: Build macOS App
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build macOS App
        run: pyinstaller build_mac.spec

      - name: Create DMG File
        run: |
          mkdir -p dmg_root
          cp -R dist/*.app dmg_root/
          hdiutil create -volname MyApp -srcfolder dmg_root -ov -format UDZO macos_build.dmg

      - name: Upload macOS DMG
        uses: actions/upload-artifact@v4
        with:
          name: macos-dmg
          path: macos_build.dmg